# Generated by Django 4.0.2 on 2022-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobileno',
            field=models.IntegerField(max_length=10),
        ),
    ]
