# Generated by Django 4.0.2 on 2022-02-18 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_doctor_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobileno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
